### PR TITLE
14 mig connector prestashop

### PR DESCRIPTION
**Pull request by florian-dacosta**
Hello @hailangvn 
I saw you made a PR into the OCA for the module connector_prestashop for v14.
I'd like to merge some fixes I've made that are not in yet.
This branch I want to merge is used in production in one instance since the beginning of the year.

### CODE REVIEW

**Comment by florian-dacosta** [comment]
@hailangvn Do you think we can merge this ?

**Comment by hailangvn** [comment]
Thanks @florian-dacosta for your PR. Tests are failing so it will take some time before we can merge.

**Comment by hailangvn** [comment]
Good day @florian-dacosta, the branch has been updated.

**Comment by florian-dacosta** [comment]
Thanks !

**Pull request merged**
